create table NOTICE(
     ID INT,
     TITLE VARCHAR(100),
     WRITER_ID VARCHAR(50),
     CONTENT VARCHAR(3000),
     REGDATE DATETIME,
     HIT INT,
     FILES VARCHAR(5000)
     );

CREATE TABLE ROLE(
     ID VARCHAR(50),
     DISCRIPTION VARCHAR(500)
     );

CREATE TABLE MEMBER_ROLE(
     MEMBER_ID VARCHAR(50),
     ROLE_ID VARCHAR(50)
     );

CREATE TABLE COMMENT(
     ID INT,
     CONTENT VARCHAR(2000),
     REGDATE DATETIME,
     WRITER_ID VARCHAR(50),
     NOTICE_ID INT
     );

CREATE TABLE MEMBER(
     ID VARCHAR(50),
     PWD VARCHAR(50),
     NAME VARCHAR(50),
     GENDER VARCHAR(2),
     BIRTHDAY VARCHAR(10),
     PHONE VARCHAR(13),
     REGDATE DATETIME,
     EMAIL VARCHAR(200)
     );